### ISSUE TITLE
Flatpak missing skrooge_import_ofx.so, so OFX/QFX import is gone from Import filter list

### ISSUE THREAD

**Issue by miraks31** [flathub/org.kde.skrooge#5]
Hi,

I'm the main developer of Skrooge and I'm very happy with what you did to publish a flatpack pakage.

Nevertheless, as you can see here (https://bugs.kde.org/show_bug.cgi?id=405099) a user opened a bug because the format ofx is not available. This happen when libofx is not installed when the build is launched.

Could you correct this in your package?

Thank you in advance.

**Comment by bilelmoussaoui** [comment]
Hey,

I have tried to reach you out and ask you if you want to co-maintain the package or interested in Flatpaking the app in general from your website. 
I will add libofx to the manifest tomorrow.
Thanks!

**Comment by miraks31** [comment]
Hi,
I don't know how to package for flatpack. 
Moreover, this takes time to generate all packages (appimage, flatpack, snap ...), so if you can do it, this is perfect for me ;-).
On my website, I put a link to flathub (https://skrooge.org/download).
Anyway, thank you a lot for what you do to provide this package.
Regards.

**Comment by eszlari** [comment]
>  I don't know how to package for flatpack.

It's not hard. In simplest case, you just have to update the URL and checksum of you release tarball at the end of the manifest:

```
    sources:
      - type: archive
        url: https://download.kde.org/stable/skrooge/skrooge-2.18.0.tar.xz
        sha256: 4671dfe736d92c2de51a872b49bfbdc251e7e869b5672b6546b85aca4409f303
```


> Moreover, this takes time to generate all packages (appimage, flatpack, snap ...)

You don't need to build the app yourself locally. If you open a PR here on Github, a test build will be started automatically and you can install the binary from Flathub, see e.g.: PR https://github.com/flathub/org.kde.skrooge/pull/4 (same for the final build)
